### PR TITLE
Add "Rebuild product-details" settings item

### PR DESCRIPTION
**Pull request by rail**

### CODE REVIEW

**Comment by rail** [comment]
I pushed this to https://shipit.staging.mozilla-releng.net/, you can see next to the use icon.

**Comment by rail** [comment]
@mozbhearsum can you review this

**Comment by mozbhearsum** [comment]
> @mozbhearsum can you review this

Yes! I presume this would remove the need for the rebulid product details part of #415?

**Comment by rail** [comment]
> I presume this would remove the need for the rebulid product details part of #415?

At least it won't be urgent to fix that.

**Pull request merged**
