### PR TITLE
Update LATEST_THUNDERBIRD_VERSION from comm-release

### PR DESCRIPTION
**Pull request by coreycb**
With this change, LATEST_THUNDERBIRD_VERSION will specify the latest monthly version of Thunderbird.

### CODE REVIEW

**Comment by jcristau** [comment]
@jfx2006 would you mind reviewing this?

**Comment by jfx2006** [comment]
Approved.
This effectively undoes 66e3696c753a105fdeea0cf2ab48bbd0400542dc and f979505cf8f45c436d1879728b1936790cd6519d and starts using the version from comm-release.

**Review by jcristau — APPROVED** [review]
Thanks.  Do you need this deployed at/by a particular date/time?

**Comment by jfx2006** [comment]
Tuesday Oct 1 would work. Or close to that if you have another deployment planned with next weeks releases.

**Comment by jcristau** [comment]
Sounds good.  We'll have one on Tuesday for #1559 anyway.

**Pull request merged**
