### PR TITLE
Add an Android icon to the pending Android releases

### LINKED ISSUE #1508: Add an Android icon to the pending Android releases
To help distinguish Dekstop and Android releases, please add an icon in the ship-it Pending Releases UI for Android releases.
https://pictogrammers.com/library/mdi/icon/android/

### PR DESCRIPTION
**Pull request by gabrielBusta**
Closes #1508

### CODE REVIEW

**Comment by gabrielBusta** [comment]
Screenshot 2024-06-27 at 17 22 50

**Comment by gabrielBusta** [comment]
Screenshot 2024-06-27 at 17 34 31

**Comment by gabrielBusta** [comment]
Screenshot 2024-06-27 at 17 50 10

**Comment by gabrielBusta** [comment]
Screenshot 2024-06-27 at 17 55 02

**Review by gbrownmozilla — APPROVED** [review]
Now you're getting fancy!

**Pull request merged**
