### PR TITLE
Bug 1717527 - add ESR91

### PR DESCRIPTION
**Pull request by jcristau**
As far as I can tell it should be safe to set ESR_NEXT already.  There are 2 users, in `api/src/shipit_api/admin/product_details.py`:
- `get_product_categories` won't find anything that matches `91(\.[0-9]+){1,2}esr$` until the 91.0esr release
- `get_firefox_esr_next_version`'s call into `get_latest_version` won't find anything with `branch` set to `releases/mozilla-esr91`, and thus it will still return an empty string, until 91.0esr ships

### CODE REVIEW

**Comment by MihaiTabara** [comment]
@jcristau just to confirm, is this ready for review? if so @mozilla-releng/releng is probably best to tag.

**Comment by jcristau** [comment]
@MihaiTabara yes please.

**Comment by MihaiTabara** [comment]
CC @bhearsum @sarah-clements this is ready for review.

**Comment by MihaiTabara** [comment]
TIL adding comments to this repo triggers more CI automation.

**Review by escapewindow — APPROVED** [review]
Stamping, not sure about alternative... but lgtm

**Review by sarah-clements — APPROVED** [review]
I think this looks ok, but Ben is probably the best person to check this.

**Review by bhearsum — APPROVED** [review]

**Pull request merged**
